spring:
  application:
    name: first-api
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db.czy2ae0cuf8j.us-east-2.rds.amazonaws.com:5432/users
    username: postgres
    password: trainibit
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true