-- public.users definition

-- Drop table

-- DROP TABLE users;

CREATE TABLE users (
                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                       "name" varchar NOT NULL,
                       last_name varchar NOT NULL,
                       email varchar NOT NULL,
                       birthday date NULL,
                       created_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       updated_date timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       "uuid" uuid NULL,
                       CONSTRAINT users_pk PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE users OWNER TO postgres;
GRANT ALL ON TABLE users TO postgres;